// pet-data.js — 毛孩心語 · 22 張動物大師卡
// 對齊 BRAND_BIBLE §0 命名公約(小夢神殿 / 深度靈性解讀,不使用 AI/演算法/機器人)
// 對齊 LINE_SYSTEM §6 首次免費規則(僅 1 次)
// 22 張圖檔位置:assets/pet-{00-21}-{animal}-{arcana}.png
// 圖檔已備齊(2026-07-04 確認:pet-19-stag-judgement.png / pet-20-whale-aeon.png / pet-21-turtle-world.png)

export const petCards = [
  {
    id: 0,
    arcana: '愚者',
    arcanaEn: 'The Fool',
    animal: '布偶貓',
    animalEn: 'Ragdoll',
    image: 'assets/pet-00-ragdoll-fool.png',
    keywords: ['新開始', '純真', '冒險', '信任'],
    petReading: '這是一個全新的開始。{{petName}}用最純真的眼睛看你,牠在告訴你:放下過去的框架,讓生活重新開始。帶牠去一個從沒去過的地方散步,讓冒險成為你們的新日常。',
    situation: {
      daily: '今天適合給 {{petName}} 一個全新的小驚喜,一個新的玩具或一段沒走過的路。',
      relationship: '{{petName}} 正在學習如何與 {{otherPet}} 共處,給牠們一點時間。',
      grief: '{{petName}} 雖然離開了,但牠把最純真的愛留在你心裡。',
    },
  },
  {
    id: 1,
    arcana: '魔術師',
    arcanaEn: 'The Magician',
    animal: '雪豹',
    animalEn: 'Snow Leopard',
    image: 'assets/pet-01-snow-leopard-magician.png',
    keywords: ['創造', '主動', '顯化', '意志'],
    petReading: '{{petName}}是個天生的創造者。牠知道如何用眼神、撒嬌、耍賴讓你做牠想做的事。今天,主動為牠安排一場小遊戲,讓牠的創造力有地方發揮。',
    situation: {
      daily: '{{petName}} 今天會主動找你玩,記得回應牠的邀請。',
      relationship: '主動讓 {{petName}} 跟 {{otherPet}} 共同完成一個小任務(一起吃零食)。',
      grief: '你可以為 {{petName}} 寫一封信,把沒說完的話寫下來。',
    },
  },
  {
    id: 2,
    arcana: '女祭司',
    arcanaEn: 'The High Priestess',
    animal: '波斯貓',
    animalEn: 'Persian',
    image: 'assets/pet-02-persian-priestess.png',
    keywords: ['直覺', '神秘', '內在智慧', '靜謐'],
    petReading: '{{petName}}的安靜不是冷漠,而是一種深度。牠正在用牠的方式告訴你:有些答案不在外面,在你安靜下來的時候。今天留 10 分鐘,跟 {{petName}} 一起靜靜坐著。',
    situation: {
      daily: '{{petName}} 會主動找你抱抱,這是牠的「能量下載」。',
      relationship: '安靜觀察 {{petName}} 與 {{otherPet}} 的互動,你會發現牠們的默契。',
      grief: '{{petName}} 留下的靜謐,是給你最大的禮物。',
    },
  },
  {
    id: 3,
    arcana: '皇后',
    arcanaEn: 'The Empress',
    animal: '兔子',
    animalEn: 'Rabbit',
    image: 'assets/pet-03-rabbit-empress.png',
    keywords: ['豐盛', '滋養', '創造力', '母愛'],
    petReading: '{{petName}}是滋養你的小天使。牠讓你學會什麼是「無條件的給予」。今天,給自己跟 {{petName}} 一頓豐盛的餐,享受被照顧的感覺。',
    situation: {
      daily: '適合買 {{petName}} 一份新鮮的小點心。',
      relationship: '{{petName}} 會主動照顧 {{otherPet}},讓牠們有共處的時間。',
      grief: '{{petName}} 曾給你的滋養,不會因為離開而消失。',
    },
  },
  {
    id: 4,
    arcana: '皇帝',
    arcanaEn: 'The Emperor',
    animal: '獅子',
    animalEn: 'Lion',
    image: 'assets/pet-04-lion-emperor.png',
    keywords: ['權威', '結構', '領導', '守護'],
    petReading: '{{petName}}是家裡的小守護者。牠會記住每一個家人回家的時間,守在門口等。今天,讓 {{petName}} 當一天的主角,做牠想做的事。',
    situation: {
      daily: '{{petName}} 今天會守在某個定點(可能是門口或窗邊),留意家裡的動靜。',
      relationship: '{{petName}} 會主動保護較小的 {{otherPet}},讓牠有被照顧的感覺。',
      grief: '{{petName}} 守護你的那段時間,是你最安全的時光。',
    },
  },
  {
    id: 5,
    arcana: '教皇',
    arcanaEn: 'The Hierophant',
    animal: '狐狸',
    animalEn: 'Fox',
    image: 'assets/pet-05-fox-hierophant.png',
    keywords: ['傳統', '信念', '引導', '智慧傳承'],
    petReading: '{{petName}}像個小老師。牠的習慣、牠的儀式感,都在教導你「日常的珍貴」。今天,跟著 {{petName}} 的節奏走,不要打破牠的習慣。',
    situation: {
      daily: '{{petName}} 的每日散步路線是神聖的儀式,別臨時改變。',
      relationship: '讓 {{petName}} 帶領 {{otherPet}} 認識家裡的規矩。',
      grief: '{{petName}} 教會你的「日常儀式感」,會繼續陪著你。',
    },
  },
  {
    id: 6,
    arcana: '戀人',
    arcanaEn: 'The Lovers',
    animal: '天鵝',
    animalEn: 'Swans',
    image: 'assets/pet-06-swans-lovers.png',
    keywords: ['選擇', '結合', '和諧', '靈魂契合'],
    petReading: '{{petName}}是你靈魂契合的伴侶。牠跟你的關係不是主人與寵物,而是兩顆互相選擇的靈魂。今天,看著 {{petName}} 的眼睛 30 秒,謝謝牠的選擇。',
    situation: {
      daily: '{{petName}} 今天會比平常更黏你,這是牠的「靈魂告白」。',
      relationship: '{{petName}} 跟 {{otherPet}} 的關係正在進入新階段,留意牠們的肢體語言。',
      grief: '{{petName}} 選擇了你,這是這輩子最珍貴的緣分。',
    },
  },
  {
    id: 7,
    arcana: '戰車',
    arcanaEn: 'The Chariot',
    animal: '馬',
    animalEn: 'Horse',
    image: 'assets/pet-07-horse-chariot.png',
    keywords: ['意志', '勝利', '推進', '前進'],
    petReading: '{{petName}}是往前衝的小戰士。牠的活力提醒你:有些事,該動了。今天帶 {{petName}} 一起完成一個「小目標」,讓動能延續到你身上。',
    situation: {
      daily: '今天適合跟 {{petName}} 一起跑步或快走 20 分鐘。',
      relationship: '{{petName}} 跟 {{otherPet}} 可能會有追逐遊戲,這是健康的能量流動。',
      grief: '{{petName}} 衝刺的姿態,會永遠留在你腦海裡。',
    },
  },
  {
    id: 8,
    arcana: '力量',
    arcanaEn: 'Strength',
    animal: '老虎',
    animalEn: 'Tiger',
    image: 'assets/pet-08-tiger-strength.png',
    keywords: ['勇氣', '耐心', '柔韌', '內在力量'],
    petReading: '{{petName}}是溫柔的勇者。牠不靠吼叫,而是靠安靜的力量。今天,當你感到疲憊時,讓 {{petName}} 靠在你的腳邊,感受那股不張揚的勇氣。',
    situation: {
      daily: '{{petName}} 今天會在某個角落靜靜守護你,留意牠的位置。',
      relationship: '{{petName}} 對 {{otherPet}} 展現的是柔韌的包容,值得你學習。',
      grief: '{{petName}} 給你的勇氣,會陪你走過接下來的每一天。',
    },
  },
  {
    id: 9,
    arcana: '隱者',
    arcanaEn: 'The Hermit',
    animal: '貓頭鷹',
    animalEn: 'Owl',
    image: 'assets/pet-09-owl-hermit.png',
    keywords: ['內省', '智慧', '指引', '獨處'],
    petReading: '{{petName}}需要一些獨處的時間。牠在角落觀察這個家,也在觀察你。今天,給 {{petName}} 一個安靜的小窩,讓牠可以思考牠的小日子。',
    situation: {
      daily: '{{petName}} 今天可能會躲在衣櫥或沙發下,這是正常的「隱者時間」。',
      relationship: '讓 {{petName}} 跟 {{otherPet}} 有各自的空間。',
      grief: '給自己一段「隱者時間」,懷念 {{petName}}。',
    },
  },
  {
    id: 10,
    arcana: '命運之輪',
    arcanaEn: 'Wheel of Fortune',
    animal: '變色龍',
    animalEn: 'Chameleon',
    image: 'assets/pet-10-chameleon-wheel.png',
    keywords: ['循環', '轉變', '機運', '順流'],
    petReading: '生命的輪正在轉動。{{petName}}也在跟著變,適應新的季節、新的家人、新的你。今天,接受變化,順流就好。',
    situation: {
      daily: '{{petName}} 今天可能會比平常安靜或活潑,都是正常的週期變化。',
      relationship: '{{petName}} 跟 {{otherPet}} 的關係可能進入新循環,給時間。',
      grief: '生命的輪會一直轉,{{petName}} 會在轉動中與你相遇。',
    },
  },
  {
    id: 11,
    arcana: '吊人',
    arcanaEn: 'The Hanged Man',
    animal: '蝙蝠',
    animalEn: 'Bat',
    image: 'assets/pet-11-bat-hanged-man.png',
    keywords: ['犧牲', '等待', '新視角', '換位'],
    petReading: '{{petName}}用倒掛的姿勢看世界。牠在告訴你:換個角度,一切都不同了。今天試著從 {{petName}} 的視角看這個家,你會發現新的風景。',
    situation: {
      daily: '{{petName}} 今天可能會在某個「奇怪」的位置休息,這是牠的創意。',
      relationship: '試著用 {{petName}} 的視角看 {{otherPet}}。',
      grief: '換個視角懷念 {{petName}},會看到不同的美。',
    },
  },
  {
    id: 12,
    arcana: '死神',
    arcanaEn: 'Death',
    animal: '蛇',
    animalEn: 'Snake',
    image: 'assets/pet-12-snake-death.png',
    keywords: ['結束', '轉化', '重生', '蛻變'],
    petReading: '一個階段正在結束,新的正在開始。{{petName}}也會經歷蛻皮——無論是身體上的換毛,還是行為上的改變。今天,放下不再需要的,迎接新生的能量。',
    situation: {
      daily: '{{petName}} 今天可能會脫毛或脫皮,這是正常的能量更新。',
      relationship: '結束 {{petName}} 跟 {{otherPet}} 的一個舊模式,讓新關係開始。',
      grief: '{{petName}} 的離開是靈魂的重生,牠在你心裡永遠活著。',
    },
  },
  {
    id: 13,
    arcana: '節制',
    arcanaEn: 'Temperance',
    animal: '金魚',
    animalEn: 'Goldfish',
    image: 'assets/pet-13-goldfish-temperance.png',
    keywords: ['平衡', '整合', '耐心', '和諧'],
    petReading: '{{petName}}教會你什麼是「剛剛好」。不多不少的飯量、不急不徐的步伐。今天,跟 {{petName}} 一起練習「節制」:少一點滑手機,多一點陪牠。',
    situation: {
      daily: '{{petName}} 的進食時間是固定的,跟著牠的節奏走。',
      relationship: '在 {{petName}} 跟 {{otherPet}} 之間取得平衡的陪伴時間。',
      grief: '{{petName}} 教會你的「平衡」,會繼續指引你的生活。',
    },
  },
  {
    id: 14,
    arcana: '惡魔',
    arcanaEn: 'The Devil',
    animal: '黑貓',
    animalEn: 'Black Cat',
    image: 'assets/pet-14-blackcat-devil.png',
    keywords: ['執著', '誘惑', '束縛', '陰影面'],
    petReading: '{{petName}}也有牠的「小陰影」——可能是抓沙發、偷食物、深夜嚎叫。今天,正視這些小怪癖,背後藏著的是未被滿足的需求。',
    situation: {
      daily: '{{petName}} 今天可能會調皮搗蛋,這是牠在表達「我需要關注」。',
      relationship: '{{petName}} 對 {{otherPet}} 可能有「地盤」意識,需要更多空間。',
      grief: '{{petName}} 那些「小毛病」,現在回想起來都是最可愛的回憶。',
    },
  },
  {
    id: 15,
    arcana: '高塔',
    arcanaEn: 'The Tower',
    animal: '公雞',
    animalEn: 'Rooster',
    image: 'assets/pet-15-rooster-tower.png',
    keywords: ['崩毀', '覺醒', '重建', '突發'],
    petReading: '今天可能會有突發狀況——{{petName}}打翻了什麼、撞倒了什麼。別生氣,這是能量釋放。清理完,你會發現家裡變得更整齊。',
    situation: {
      daily: '{{petName}} 今天可能會大動作,把東西撥到地上,讓牠吧。',
      relationship: '{{petName}} 跟 {{otherPet}} 可能會有「小衝突」,冷靜一下就好。',
      grief: '{{petName}} 走後,家裡突然變安靜——這是另一種「塔」,需要時間重建。',
    },
  },
  {
    id: 16,
    arcana: '星星',
    arcanaEn: 'The Star',
    animal: '鳳凰',
    animalEn: 'Phoenix',
    image: 'assets/pet-16-phoenix-star.png',
    keywords: ['希望', '靈感', '療癒', '重生之光'],
    petReading: '{{petName}}是照亮你的小星星。牠的存在本身就是希望。今天,看著 {{petName}} 的眼睛,你會看到自己被療癒了。',
    situation: {
      daily: '{{petName}} 今天會主動靠近你,讓你感受到溫暖。',
      relationship: '{{petName}} 是 {{otherPet}} 的「希望燈塔」,牠們會互相照耀。',
      grief: '{{petName}} 是你心裡那顆永遠的星星,不會熄滅。',
    },
  },
  {
    id: 17,
    arcana: '月亮',
    arcanaEn: 'The Moon',
    animal: '狼',
    animalEn: 'Wolf',
    image: 'assets/pet-17-wolf-moon.png',
    keywords: ['潛意識', '直覺', '幻象', '夜間智慧'],
    petReading: '夜晚是 {{petName}} 的祕密時光。牠在月光下走動、發出奇怪的聲音,這是牠的「靈魂對話」。今天,睡前留一盞小燈,讓 {{petName}} 安心。',
    situation: {
      daily: '{{petName}} 晚上會特別活躍,這是正常的「夜間能量」。',
      relationship: '{{petName}} 跟 {{otherPet}} 晚上會組成「小狼群」,一起巡邏家裡。',
      grief: '夜晚想念 {{petName}} 時,看月亮就好。',
    },
  },
  {
    id: 18,
    arcana: '太陽',
    arcanaEn: 'The Sun',
    animal: '蝴蝶',
    animalEn: 'Butterfly',
    image: 'assets/pet-18-butterfly-sun.png',
    keywords: ['喜悅', '成功', '活力', '光明'],
    petReading: '{{petName}}今天會帶來滿滿的喜悅。陽光灑進來時,看著牠在窗邊打盹,那就是「幸福」的具體形狀。',
    situation: {
      daily: '今天帶 {{petName}} 去曬曬太陽,20 分鐘就好。',
      relationship: '{{petName}} 跟 {{otherPet}} 會在陽光下一起「日光浴」。',
      grief: '想起 {{petName}} 時,溫暖就是想念最美的樣子。',
    },
  },
  {
    id: 19,
    arcana: '審判',
    arcanaEn: 'Judgement',
    animal: '鹿',
    animalEn: 'Stag',
    image: 'assets/pet-19-stag-judgement.png',
    keywords: ['覺醒', '召喚', '寬恕', '新生'],
    petReading: '{{petName}}是溫柔的覺醒者。牠用無辜的眼神召喚你:放下過去的罪惡感,接受自己是好主人。{{petName}} 已經原諒你所有的「不夠好」了。今天,你也原諒自己。',
    situation: {
      daily: '{{petName}} 今天會在你身邊安靜地待著,讓你感受到「被接納」。',
      relationship: '{{petName}} 對 {{otherPet}} 的接納是無條件的,跟著牠學。',
      grief: '原諒自己當時沒有做到的一切 — {{petName}} 已經原諒你了。',
    },
  },
  {
    id: 20,
    arcana: '永恆 / Aeons',
    arcanaEn: 'The Aeon',
    animal: '鯨',
    animalEn: 'Whale',
    image: 'assets/pet-20-whale-aeon.png',
    keywords: ['永恆', '深層智慧', '集體潛意識', '靈魂長眠'],
    petReading: '{{petName}}是永恆的靈魂伴侶。牠在你的生命裡很短,但在靈魂層面,牠永遠與你同在。今天,允許自己悲傷,因為悲傷是通往永恆的橋。',
    situation: {
      daily: '今天想念 {{petName}} 時,閉眼感受胸口的溫熱,那就是牠。',
      relationship: '{{petName}} 跟 {{otherPet}} 的緣分也是永恆的,跨越生死。',
      grief: '{{petName}} 沒有離開,牠只是變成另一種形式,繼續陪伴你。',
    },
  },
  {
    id: 21,
    arcana: '世界',
    arcanaEn: 'The World',
    animal: '龜',
    animalEn: 'Turtle',
    image: 'assets/pet-21-turtle-world.png',
    keywords: ['完成', '整合', '成就', '圓滿'],
    petReading: '你跟 {{petName}} 的旅程正在畫下一個圓。這不代表結束,而是更高層次的開始。今天,謝謝 {{petName}} 用這一生教會你的一切,你已經是一個更好的人了。',
    situation: {
      daily: '今天跟 {{petName}} 一起完成一個「小儀式」:一個抱抱、一個散步、一頓飯。',
      relationship: '{{petName}} 跟 {{otherPet}} 的故事,正在寫下圓滿的一頁。',
      grief: '{{petName}} 的一生是完整的,你的悲傷也是完整的一部分。',
    },
  },
];

export const petSituationLabels = {
  daily: '日常陪伴',
  relationship: '關係探索',
  grief: '離世悼念',
};

export const petSystemMeta = {
  name: '毛孩心語',
  nameEn: 'Pet Divination',
  totalCards: 22,
  situationCount: 3,
  requiredTier: 'member', // 尊榮會員限定
  freeForFirstTime: 1,
  freeExpiryDays: 7,
  promptsFile: 'lib/prompts/pet-divination.md',
  promptStyle: '深度解析排版工具',
  note: '本系統使用 7 個情境的深度解析排版工具(日常陪伴 / 關係探索 / 行為理解 / 離世悼念 / 新成員迎接 / 健康能量 / 生命禮讚)',
};